version: '2'

services:
  pihole:
    container_name: pihole
    image: juampe/pihole-dot:latest
    restart: unless-stopped
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    environment:
      ServerIP: ${ServerIP}
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      DOT_UPSTREAM: ${DOT_UPSTREAM}
      DNS1: 127.0.0.1#5353 # Hardcoded to our Unbound server
      DNS2: null           # Hardcoded to our Unbound server
      DNSSEC: "true"       # Enable DNSSEC
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    volumes:
      - etc_pihole-unbound:/etc/pihole:rw
      - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    mac_address: ${MAC_ADDRESS}
    networks:
      pihole_vlan:
        ipv4_address: ${IPV4_ADDRESS}
    ports:
      - 443:443/tcp
      - 53:53/tcp
      - 53:53/udp
      - 8080:80/tcp
      # - 5353:5353/tcp    # Uncomment to enable unbound access on local server
      # - 22/tcp           # Uncomment to enable SSH
    cap_add:
      - NET_ADMIN
      - SYS_NICE

volumes:
  etc_pihole-unbound:
  etc_pihole_dnsmasq-unbound:

networks:
  pihole_vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
