version: "2.1"
services:
  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SERVERURL: ${DOMAIN}
      SERVERPORT: 51820
      PEERS: ${PEERS} 
      PEERDNS: auto 
      INTERNAL_SUBNET: ${INTERNAL_SUBNET}
      ALLOWEDIPS: 0.0.0.0/0
    volumes:
      - /opt/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
     - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
